apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-web-v1
  labels:
    kubernetes.azureauthority.in: deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist-web
      version: v1
  template:
    metadata:
      labels:
        app: todolist-web
        version: v1
    spec:
      containers:
        - name: app
          image: nitu1122/todo-list-web:1.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-save-handler-v2
  labels:
    kubernetes.azureauthority.in: deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist-save-handler
      version: v2
  template:
    metadata:
      labels:
        app: todolist-save-handler
        version: v2
    spec:
      containers:
        - name: app
          image: nitu1122/todo-list-save-handler
----
apiVersion: apps/v1

kind: Deployment

metadata:

  name: todo-queue-v2

  labels:

    kubernetes.azureauthority.in: deployments

spec:

  replicas: 1

  selector:

    matchLabels:

      app: todo-queue

      version: v2

  template:

    metadata:

      labels:

        app: todo-queue

        version: v2

    spec:

      containers:

        - name: app

          image: redis:6.2-alpine

          
         